services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - esports-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - esports-net

networks:
  esports-net:
    driver: bridge